---
- name: Get tomorrows date
  command:  "date +'%Y-%m-%d' -d '+1 days'"
  register: tomorrow_date

- name: Setup Daily Sync Plan
  command: /usr/bin/hammer sync-plan create --interval=daily --name='Daily sync' --organization-id=1 --enabled true --sync-date "{{tomorrow_date.stdout}} 02:00:00"
