---
## Initial configuration of Satellite Server
## Enable Standard repos
- name: enable Repos
  command: subscription-manager repos --enable {{ item }}
  with_items:
    - '{{repo_ids}}'
  when:
    - connected

- name: Initial configuration of Satellite
  command:  /usr/sbin/satellite-installer --scenario satellite --foreman-initial-organization "{{ sat_org }}" --foreman-initial-location "{{ sat_location }}" --foreman-admin-username "{{ vault_sat_admin_name }}" --foreman-admin-password "{{ vault_sat_admin_pwd }}"
