---
## Enable Standard repos
- name: enable Repos
  command: subscription-manager repos --enable {{ item }}
  with_items:
   - rhel-7-server-extras-rpms
   - rhel-7-server-optional-rpms
   - rhel-7-server-rh-common-rpms
  when: enable_repos
